spring:
  main:
    allow-circular-references: true
  application:
    name: TO_DO_APP
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shopping_online
    username: postgres
    password: 123456
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true
server:
  port: 8080